FROM python:3.13.0-alpine as base
RUN apk add --update tzdata

FROM python:3.13.0-alpine
ARG VERSION
ENV CONFIG_FILE="carconnectivity.yml"
ENV ADDITIONAL_PARAMETERS=
ENV TZ=
ENV MUSL_LOCPATH="/usr/share/i18n/locales/musl"

COPY . carconnectivity-mqtt
WORKDIR ./carconnectivity-mqtt/

# Copy zoneinfo
COPY --from=base /usr/share/zoneinfo /usr/share/zoneinfo
# Pillow depenencies
RUN apk --no-cache add --virtual build-dependencies build-base \
    && apk --no-cache add git \
                          jpeg-dev \
                          zlib-dev \
                          freetype-dev \
                          lcms2-dev \
                          openjpeg-dev \
                          tiff-dev \
                          tk-dev \
                          tcl-dev \
                          musl-locales \
                          musl-locales-lang \
    && pip install --no-cache-dir . \
    && pip install carconnectivity-connector-volkswagen carconnectivity-connector-skoda \
    && apk del build-dependencies

CMD carconnectivity-mqtt ${CONFIG_FILE} ${ADDITIONAL_PARAMETERS}